# Data Cleaning # 

> There are Three Types 

## MCAR: Missing Completely at Random

- Missing values have no pattern at all
- The missing value is random
- Not related to any other columns

> safe to 

    drop rows
    fill with mean/median


## MAR: Missing At Random

- Missing depends on another Column

> Age missing Depends on Gender: Females usually dont fill age 

> Do: 
- group-based filling

## MNAR: Missing Not at Random

- Missing depends on itself (hidden reason)

    High-income people don’t reveal salary
    So high salaries = missing

Dangerous:

    Mean/median filling → wrong

✔ Better:
    
    create new feature:

In [1]:
import pandas as pd
import numpy as np

In [7]:
df = pd.read_csv("messy_dataset_for_cleaning.csv")

In [8]:
df

,customer_age,annual_income_k,credit_score,purchase_frequency,avg_transaction_value,days_since_last_purchase,total_return_amount,num_support_tickets,website_visits_30d,email_open_rate_pct,...,messy_column_21,messy_column_22,messy_column_23,messy_column_24,messy_column_25,messy_column_26,messy_column_27,messy_column_28,messy_column_29,messy_column_30
0,21.0,39.2,640.0,NaN,NaN,16.0,NaN,8.0,56.0,41.9,...,unknown,missing,missing,NaN,missing,unknown,NaN,missing,value_10,value_2
1,NaN,20.0,728.0,12.0,63.60,40.0,31.75,NaN,3.0,70.1,...,NaN,NaN,missing,NaN,NaN,NaN,missing,NaN,???,NaN
2,55.0,20.0,660.0,17.0,5.00,1.0,33.56,NaN,1.0,45.4,...,NaN,???,NaN,NaN,missing,NaN,NaN,missing,NaN,NaN
3,66.0,NaN,NaN,22.0,5.00,6.0,38.72,8.0,3.0,27.1,...,unknown,missing,NaN,missing,value_10,???,NaN,value_2,NaN,missing
4,57.0,65.3,684.0,11.0,73.03,9.0,74.25,0.0,3.0,23.3,...,value_7,value_8,NaN,???,NaN,NaN,unknown,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5145,69.0,NaN,670.0,11.0,299.43,51.0,187.47,1.0,102.0,32.2,...,missing,value_10,NaN,NaN,NaN,NaN,NaN,NaN,missing,missing
5146,53.0,126.3,690.0,NaN,131.46,18.0,NaN,2.0,14.0,33.7,...,???,NaN,NaN,???,???,NaN,NaN,NaN,???,missing
5147,69.0,45.9,705.0,21.0,182.17,47.0,25.16,0.0,NaN,NaN,...,NaN,NaN,NaN,NaN,unknown,NaN,NaN,NaN,NaN,NaN
5148,64.0,59.9,748.0,7.0,49.22,NaN,NaN,2.0,1.0,25.0,...,NaN,value_9,missing,NaN,missing,???,???,NaN,NaN,???
5149,24.0,37.1,724.0,10.0,NaN,28.0,NaN,0.0,2.0,39.1,...,unknown,???,value_6,missing,unknown,NaN,???,NaN,???,NaN

In [10]:
df.shape

(5150, 61)

In [11]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5150 entries, 0 to 5149
Data columns (total 61 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_age              4357 non-null   float64
 1   annual_income_k           4505 non-null   float64
 2   credit_score              4743 non-null   float64
 3   purchase_frequency        4672 non-null   float64
 4   avg_transaction_value     4258 non-null   float64
 5   days_since_last_purchase  4104 non-null   float64
 6   total_return_amount       3877 non-null   float64
 7   num_support_tickets       3969 non-null   float64
 8   website_visits_30d        4434 non-null   float64
 9   email_open_rate_pct       4341 non-null   float64
 10  customer_lifetime_value   4155 non-null   float64
 11  cancellation_risk_score   4459 non-null   float64
 12  customer_segment          3411 non-null   str
 13  payment_method            3407 non-null   str
 14  subscription_tier         4541 non-null   str
 15  country_code              4367 non-null   str
 16  device_type               4590 non-null   str
 17  browser                   4588 non-null   str
 18  gender                    3760 non-null   str
 19  employment_status         4644 non-null   str
 20  marital_status            3545 non-null   str
 21  education_level           4679 non-null   str
 22  signup_date               4327 non-null   str
 23  last_login                5150 non-null   str
 24  subscription_end_date     3893 non-null   str
 25  customer_feedback         3524 non-null   str
 26  promo_code_used           3454 non-null   str
 27  referral_source           3698 non-null   str
 28  customer_status           3994 non-null   str
 29  timezone                  3890 non-null   str
 30  newsletter_subscribed     4252 non-null   str
 31  messy_column_01           2268 non-null   str
 32  messy_column_02           2300 non-null   str
 33  messy_column_03           2297 non-null   str
 34  messy_column_04           2295 non-null   str
 35  messy_column_05           2324 non-null   str
 36  messy_column_06           2241 non-null   str
 37  messy_column_07           2278 non-null   str
 38  messy_column_08           2310 non-null   str
 39  messy_column_09           2350 non-null   str
 40  messy_column_10           2319 non-null   str
 41  messy_column_11           2311 non-null   str
 42  messy_column_12           2290 non-null   str
 43  messy_column_13           2281 non-null   str
 44  messy_column_14           2304 non-null   str
 45  messy_column_15           2262 non-null   str
 46  messy_column_16           2289 non-null   str
 47  messy_column_17           2316 non-null   str
 48  messy_column_18           2341 non-null   str
 49  messy_column_19           2272 non-null   str
 50  messy_column_20           2271 non-null   str
 51  messy_column_21           2193 non-null   str
 52  messy_column_22           2345 non-null   str
 53  messy_column_23           2257 non-null   str
 54  messy_column_24           2263 non-null   str
 55  messy_column_25           2285 non-null   str
 56  messy_column_26           2277 non-null   str
 57  messy_column_27           2279 non-null   str
 58  messy_column_28           2324 non-null   str
 59  messy_column_29           2249 non-null   str
 60  messy_column_30           2308 non-null   str
dtypes: float64(12), str(49)
memory usage: 3.4 MB

In [17]:
missing_values = df.isnull().sum().sort_values(ascending = False)
missing_values

messy_column_21       2957
messy_column_06       2909
messy_column_29       2901
messy_column_23       2893
messy_column_15       2888
                      ...
employment_status      506
purchase_frequency     478
education_level        471
credit_score           407
last_login               0
Length: 61, dtype: int64

In [18]:
# Missing percentage 

missing_values / len(df) * 100

messy_column_21       57.417476
messy_column_06       56.485437
messy_column_29       56.330097
messy_column_23       56.174757
messy_column_15       56.077670
                        ...
employment_status      9.825243
purchase_frequency     9.281553
education_level        9.145631
credit_score           7.902913
last_login             0.000000
Length: 61, dtype: float64

In [19]:
# Standardized Col Names

df.columns = df.columns.str.strip().str.lower().str.replace(" ","_")

In [20]:
df.head(3)

,customer_age,annual_income_k,credit_score,purchase_frequency,avg_transaction_value,days_since_last_purchase,total_return_amount,num_support_tickets,website_visits_30d,email_open_rate_pct,...,messy_column_21,messy_column_22,messy_column_23,messy_column_24,messy_column_25,messy_column_26,messy_column_27,messy_column_28,messy_column_29,messy_column_30
0,21.0,39.2,640.0,NaN,NaN,16.0,NaN,8.0,56.0,41.9,...,unknown,missing,missing,NaN,missing,unknown,NaN,missing,value_10,value_2
1,NaN,20.0,728.0,12.0,63.6,40.0,31.75,NaN,3.0,70.1,...,NaN,NaN,missing,NaN,NaN,NaN,missing,NaN,???,NaN
2,55.0,20.0,660.0,17.0,5.0,1.0,33.56,NaN,1.0,45.4,...,NaN,???,NaN,NaN,missing,NaN,NaN,missing,NaN,NaN

# Check Wrong Data Types