In [43]:
import pandas as pd 
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
import dill

___

# Load The Dataset 

```
Outpute Features is " Estimated Salary " 
```
___

In [44]:
data = pd.read_csv("/home/aizen/AI_ML/18.Deep_Learning/1_ANN/Classification/Churn_Modelling.csv")
data

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

___

# PreProcessing Data
___

In [45]:
# Drop Irrelavent Cols 

data = data.drop(["RowNumber", "CustomerId", "Surname"], axis = 1)

In [46]:
data

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

```
Geography & Gneder are Categorical Featutes Encode them

In [47]:
label_encoder_gender = LabelEncoder()
data["Gender"] = label_encoder_gender.fit_transform(data["Gender"])

In [48]:
data

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,0,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,0,41,1,83807.86,1,0,1,112542.58,0
2,502,France,0,42,8,159660.80,3,1,0,113931.57,1
3,699,France,0,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,0,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,1,39,5,0.00,2,1,0,96270.64,0
9996,516,France,1,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,0,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,1,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,0,28,4,130142.79,1,1,0,38190.78,0

In [49]:
# use OHE for Geography Feature

from sklearn.preprocessing import OneHotEncoder

ohe_encoder_geo = OneHotEncoder(sparse_output=False, handle_unknown="ignore")

geo_encoded = ohe_encoder_geo.fit_transform(data[["Geography"]])

In [50]:
ohe_encoder_geo.get_feature_names_out()

array(['Geography_France', 'Geography_Germany', 'Geography_Spain'],
      dtype=object)

In [51]:
geo_encoded_df = pd.DataFrame(
    geo_encoded,
    columns=ohe_encoder_geo.get_feature_names_out()
)

In [52]:
# print Geo encoded Df 
geo_encoded_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [53]:
data = pd.concat(
    [   data.drop("Geography", axis = 1),
        geo_encoded_df],
    axis=1
)

In [54]:
data

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,771,1,39,5,0.00,2,1,0,96270.64,0,1.0,0.0,0.0
9996,516,1,35,10,57369.61,1,1,1,101699.77,0,1.0,0.0,0.0
9997,709,0,36,7,0.00,1,0,1,42085.58,1,1.0,0.0,0.0
9998,772,1,42,3,75075.31,2,1,0,92888.52,1,0.0,1.0,0.0
9999,792,0,28,4,130142.79,1,1,0,38190.78,0,1.0,0.0,0.0

___
# Save Encoder pickles in Artifact 
___

In [55]:
import os 

os.makedirs("artifact", exist_ok = True
)

with open("artifact/label_encoder_gender.pkl", "wb") as file:
    dill.dump(label_encoder_gender, file)


with open("artifact/ohe_encoder_geo.pkl", "wb") as file:
    dill.dump(ohe_encoder_geo, file)

____
# X and Y SPlit 
____

In [56]:
X = data.drop("EstimatedSalary", axis = 1)
y = data["EstimatedSalary"]

___
# Train Test Split
___

In [57]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.20, random_state=42)

___
# Scaler 
___

In [58]:
scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

## save scaer

In [59]:
with open("artifact/scaler.pkl", "wb") as file:
    dill.dump(scaler, file)

____
____
____

# ANN Implementation

___
___
___

In [60]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
import datetime

___

### Input Nodes:
  See X_train_scaled.shape that many will be our input Nodes/Features

### Hiden Layer: 
  Hidden layer is created using Dense

        e.g I created Hidden Layer One with 60 Nodes ( you can Choose as many ) 
            I need to give input Shape to this Dense so that it Knows How many Inputs are comming

___

In [61]:
X_train_scaled.shape[1]

12

___

# Sequential and Dense in Keras

## Sequential

`Sequential` is used to **build the neural network by adding layers one after another**.

```text
Input
  ↓
Dense Layer
  ↓
Dense Layer
  ↓
Output
```

### SynTax:

```python 
model = Sequential([
    layer1,
    layer2,
    layer3
])
```


## Dense

Dense represents a fully connected layer of neurons.

Each neuron receives input from all neurons in the previous layer.

### Syntax

```python 
Dense(
    number_of_neurons,
    activation="activation_function"
)

```

## Using Both Together

> We use Sequential to create the model and Dense to create its layers.

```Text
10 Input Features
       ↓
Dense → 64 Neurons → ReLU
       ↓
Dense → 32 Neurons → ReLU
       ↓
Dense → 1 Neuron → Sigmoid
       ↓
Prediction

```

> Sequential = the structure/container of the ANN

> Dense = the actual layers/neurons inside the ANN

___

In [62]:
model = Sequential ( 
    [
    Dense(64, activation = "relu", input_shape = (X_train_scaled.shape[1],)), # HL1
    Dense(32, activation = "relu"),  # HL2
    Dense(1) # in the Outlayer I didnt apply any Function ( by default it wll take Linear Act Fuction)
    ]
)

/home/aizen/miniconda3/envs/gensim-env/lib/python3.12/site-packages/keras/src/layers/core/dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [63]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_6 (Dense)                 │ (None, 64)             │           832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_7 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_8 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,945 (11.50 KB)

 Trainable params: 2,945 (11.50 KB)

 Non-trainable params: 0 (0.00 B)

___

# Model Compilation

`compile()` tells the ANN **how to learn**.

It mainly defines:

- **Optimizer** → How weights are updated
- **Loss** → How wrong the predictions are
- **Metrics** → How performance is measured

### Syntax

```python
model.compile(
    optimizer="adam",
    loss="binary_crossentropy",
    metrics=["accuracy"]
)

```
```
To do forward and Backword Propagation we need to Compile the Model
```

> Remember: compile() prepares the model for training; it does not train the model

___

In [64]:
# To Indrectly Set and Optimizer, Activatvation Functions and Loss Function we can use this 


import tensorflow
opt = tensorflow.keras.optimizers.Adam(learning_rate = 0.001)

In [65]:
model.compile(
    optimizer = opt,
    loss = "mean_absolute_error",
    metrics = ["mae"]
)

___
## Setup Tensor Board Logs before Training

In [66]:
import datetime

from tensorflow.keras.callbacks import EarlyStopping, TensorBoard


# Create a unique directory for TensorBoard logs
# Example:
# logs/fit/20260903-151200
log_dir = "logs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")


# Create the TensorBoard callback
# histogram_freq=1 means TensorBoard will record
# weight/activation histograms after every epoch.
tensorflow_callback = TensorBoard(
    log_dir=log_dir,
    histogram_freq=1
)

___
# Early Stopping

## What is Early Stopping?

**Early Stopping** is a technique used during model training to **stop training automatically when the model stops improving**.

Instead of training for a fixed number of epochs, we monitor a metric such as validation loss.

---

## Why is it Used?

It is mainly used to:

- Prevent **overfitting**
- Stop unnecessary training
- Save training time
- Keep the model at its **best performance**

---

## How It Works

```text
Epoch 1 → Validation Loss ↓
Epoch 2 → Validation Loss ↓
Epoch 3 → Validation Loss ↓
Epoch 4 → Validation Loss ↓
Epoch 5 → Validation Loss ↑
Epoch 6 → Validation Loss ↑
Epoch 7 → Validation Loss ↑
                 ↓
          Stop Training
```

> Usually, we use patience to allow the model a few epochs to improve before stopping.


# Important Parameters

### monitor

> The metric we want to watch.

```text
val_loss
val_accuracy
loss
accuracy
```

### patience

> Number of epochs to wait for improvement before stopping.

``` python
patience=5

If the monitored metric doesn't improve for 5 consecutive epochs, stop training.

```

### restore_best_weights

> Restores the model weights from the epoch where the monitored metric was best

## Basic Synatx

```python 
from tensorflow.keras.callbacks import EarlyStopping

early_stopping = EarlyStopping(
    monitor="val_loss",
    patience=5,
    restore_best_weights=True
)

```

> Early Stopping prevents unnecessary training and helps reduce overfitting by stopping when validation performance stops improving.

In [67]:
from tensorflow.keras.callbacks import EarlyStopping

early_stopping_callback = EarlyStopping(
    monitor = "val_loss",
    patience = 7,
    restore_best_weights = True
)

____
____

# Training The Model 


## Model Fit

`fit()` is used to **train the ANN on the training data**.

### Syntax

```python
model.fit(
    X_train,
    y_train,
    epochs=100,
    validation_data=(X_test, y_test)
)

X_train → Training features
y_train → Training labels
epochs → Number of times the model sees the complete training dataset
validation_data → Data used to check performance after each epoch
```

> Remember: compile() tells the model how to learn, while fit() actually trains the model.

___
___

In [68]:
history = model.fit(
    X_train_scaled,
    y_train,
    validation_data= (X_test_scaled, y_test),   # ← use TEST data
    epochs=100,
    callbacks=[tensorflow_callback, early_stopping_callback]
)

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 100371.2031 - mae: 100371.2031 - val_loss: 98494.4609 - val_mae: 98494.4609
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 99552.6250 - mae: 99552.6250 - val_loss: 96843.9688 - val_mae: 96843.9688
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 96678.1016 - mae: 96678.1016 - val_loss: 92636.1875 - val_mae: 92636.1875
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 91085.1719 - mae: 91085.1719 - val_loss: 85728.2344 - val_mae: 85728.2344
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 83009.5781 - mae: 83009.5781 - val_loss: 76878.5703 - val_mae: 76878.5703
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 73632.0625 - mae: 73632.0625 - val_loss: 67867.0156 - val_mae: 67867.0156
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 64767.5898 - mae: 64767.5898 - val_loss: 60285.3711 - val_mae: 60285.3711
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 57984.5781 - mae: 57984.5781 - val_loss: 55181.5078 - val_mae: 55181.5078
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 53822.7227 - mae: 53822.7227 - val_loss: 52398.5703 - val_mae: 52398.5703
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 51717.4766 - mae: 51717.4766 - val_loss: 51296.4492 - val_mae: 51296.4492
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50867.1484 - mae: 50867.1484 - val_loss: 50972.9648 - val_mae: 50972.9648
Epoch 12/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50541.3867 - mae: 50541.3867 - val_loss: 50846.8008 - val_mae: 50846.8008
Epoch 13/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50393.7617 - mae: 50393.7617 - val_loss: 50781.7734 - val_mae: 50781.7734
Epoch 14/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50302.0898 - mae: 50302.0898 - val_loss: 50733.5430 - val_mae: 50733.5430
Epoch 15/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50234.4883 - mae: 50234.4883 - val_loss: 50687.7383 - val_mae: 50687.7383
Epoch 16/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50171.0391 - mae: 50171.0391 - val_loss: 50646.2422 - val_mae: 50646.2422
Epoch 17/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50113.0039 - mae: 50113.0039 - val_loss: 50611.9688 - val_mae: 50611.9688
Epoch 18/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50063.6172 - mae: 50063.6172 - val_loss: 50569.5391 - val_mae: 50569.5391
Epoch 19/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50020.6484 - mae: 50020.6484 - val_loss: 50532.7969 - val_mae: 50532.7969
Epoch 20/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49983.1484 - mae: 49983.1484 - val_loss: 50498.2891 - val_mae: 50498.2891
Epoch 21/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49947.5898 - mae: 49947.5898 - val_loss: 50470.2734 - val_mae: 50470.2734
Epoch 22/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49916.1992 - mae: 49916.1992 - val_loss: 50437.2305 - val_mae: 50437.2305
Epoch 23/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49884.1797 - mae: 49884.1797 - val_loss: 50413.8867 - val_mae: 50413.8867
Epoch 24/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49852.5547 - mae: 49852.5547 - val_loss: 50385.7070 - val_mae: 50385.7070
Epoch 25/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49828.4336 - mae: 49828.4336 - val_loss: 50369.3906 - val_mae: 50369.3906
Epoch 26/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49804.1914 - mae: 49804.1914 - val_loss: 50354.5664 - val_mae: 50354.5664
Epoch 27/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49781.2852 - mae: 49781.2852 - val_loss: 50336.9453 - val_mae: 50336.9453
Epoch 28/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49759.2734 - mae: 49759.2734 - val_loss: 50314.7734 - val_mae: 50314.7734
Epoch 29/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49735.8633 - mae: 49735.8633 - val_loss: 50305.1055 - val_mae: 50305.1055
Epoch 30/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49719.3438 - mae: 49719.3438 - val_loss: 50287.7383 - val_mae: 50287.7383
Epoch 31/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49704.0234 - mae: 49704.0234 - val_loss: 50280.2773 - val_mae: 50280.2773
Epoch 32/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49686.3203 - mae: 49686.3203 - val_loss: 50273.4141 - val_mae: 50273.4141
Epoch 33/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49669.3477 - mae: 49669.3477 - val_loss: 50274.2578 - val_mae: 50274.2578
Epoch 34/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49655.2148 - mae: 49655.2148 - val_loss: 50261.3242 - val_mae: 50261.3242
Epoch 35/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49638.0430 - mae: 49638.0430 - val_loss: 50264.0469 - val_mae: 50264.0469
Epoch 36/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49626.2812 - mae: 49626.2812 - val_loss: 50257.8477 - val_mae: 50257.8477
Epoch 37/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49613.5391 - mae: 49613.5391 - val_loss: 50250.7227 - val_mae: 50250.7227
Epoch 38/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49601.2812 - mae: 49601.2812 - val_loss: 50254.0156 - val_mae: 50254.0156
Epoch 39/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49589.3672 - mae: 49589.3672 - val_loss: 50247.4375 - val_mae: 50247.4375
Epoch 40/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49579.8828 - mae: 49579.8828 - val_loss: 50244.6523 - val_mae: 50244.6523
Epoch 41/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49569.7656 - mae: 49569.7656 - val_loss: 50241.5078 - val_mae: 50241.5078
Epoch 42/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49562.1641 - mae: 49562.1641 - val_loss: 50243.4648 - val_mae: 50243.4648
Epoch 43/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49550.2031 - mae: 49550.2031 - val_loss: 50245.1406 - val_mae: 50245.1406
Epoch 44/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49542.2930 - mae: 49542.2930 - val_loss: 50243.2578 - val_mae: 50243.2578
Epoch 45/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49534.8867 - mae: 49534.8867 - val_loss: 50231.7617 - val_mae: 50231.7617
Epoch 46/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49525.4102 - mae: 49525.4102 - val_loss: 50232.8242 - val_mae: 50232.8242
Epoch 47/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49519.0977 - mae: 49519.0977 - val_loss: 50233.2656 - val_mae: 50233.2656
Epoch 48/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49512.6602 - mae: 49512.6602 - val_loss: 50234.2109 - val_mae: 50234.2109
Epoch 49/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49507.6055 - mae: 49507.6055 - val_loss: 50231.8203 - val_mae: 50231.8203
Epoch 50/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49501.0312 - mae: 49501.0312 - val_loss: 50224.8555 - val_mae: 50224.8555
Epoch 51/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49492.8438 - mae: 49492.8438 - val_loss: 50232.1055 - val_mae: 50232.1055
Epoch 52/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49485.8320 - mae: 49485.8320 - val_loss: 50221.5703 - val_mae: 50221.5703
Epoch 53/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49477.9297 - mae: 49477.9297 - val_loss: 50228.3047 - val_mae: 50228.3047
Epoch 54/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49470.3242 - mae: 49470.3242 - val_loss: 50228.6211 - val_mae: 50228.6211
Epoch 55/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49465.3828 - mae: 49465.3828 - val_loss: 50222.7070 - val_mae: 50222.7070
Epoch 56/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49457.6797 - mae: 49457.6797 - val_loss: 50235.2539 - val_mae: 50235.2539
Epoch 57/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49451.6055 - mae: 49451.6055 - val_loss: 50230.0078 - val_mae: 50230.0078
Epoch 58/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49446.0039 - mae: 49446.0039 - val_loss: 50218.1719 - val_mae: 50218.1719
Epoch 59/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49440.8125 - mae: 49440.8125 - val_loss: 50216.2930 - val_mae: 50216.2930
Epoch 60/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49436.1914 - mae: 49436.1914 - val_loss: 50216.5273 - val_mae: 50216.5273
Epoch 61/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49430.9062 - mae: 49430.9062 - val_loss: 50217.5898 - val_mae: 50217.5898
Epoch 62/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49422.7148 - mae: 49422.7148 - val_loss: 50223.5273 - val_mae: 50223.5273
Epoch 63/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49419.3281 - mae: 49419.3281 - val_loss: 50223.5703 - val_mae: 50223.5703
Epoch 64/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49412.4375 - mae: 49412.4375 - val_loss: 50220.6328 - val_mae: 50220.6328
Epoch 65/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49409.3945 - mae: 49409.3945 - val_loss: 50217.3242 - val_mae: 50217.3242
Epoch 66/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49403.6680 - mae: 49403.6680 - val_loss: 50221.8047 - val_mae: 50221.8047

___
# Save This Model
___

In [69]:
model.save("artifact/model.h5")

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

In [70]:
# Evaluet the mOdel 
test_loss, test_mae = model.evaluate(X_test_scaled, y_test)
test_mae

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 50216.2930 - mae: 50216.2930

50216.29296875

In [71]:
print(y_test.describe())

count      2000.000000
mean      98726.040350
std       57470.903307
min          11.580000
25%       49712.365000
50%       98511.730000
75%      147317.217500
max      199992.480000
Name: EstimatedSalary, dtype: float64

In [73]:
print(data.corr()["EstimatedSalary"].sort_values(ascending=False))

EstimatedSalary      1.000000
NumOfProducts        0.014204
Balance              0.012797
Exited               0.012097
Geography_Germany    0.010297
Tenure               0.007784
CreditScore         -0.001384
Geography_France    -0.003332
Geography_Spain     -0.006482
Age                 -0.007201
Gender              -0.008112
HasCrCard           -0.009933
IsActiveMember      -0.011421
Name: EstimatedSalary, dtype: float64

```
We Got High MAE Error cuz Esimated Salary is Random Feature Doesnt have strong corelation with any feaure

____

# Load Tensor Board Session

___

In [72]:
%load_ext tensorboard

%tensorboard --logdir logs/fit

The tensorboard extension is already loaded. To reload it, use:
  %reload_ext tensorboard

Reusing TensorBoard on port 6006 (pid 37569), started 0:13:05 ago. (Use '!kill 37569' to kill it.)